/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Bits1.h
**     Project     : ProcessorExpert
**     Processor   : MKL05Z32VLC4
**     Component   : BitsIO_LDD
**     Version     : Component 01.024, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-02-19, 02:32, # CodeGen: 27
**     Abstract    :
**         The HAL BitsIO component provides a low level API for unified
**         access to general purpose digital input/output 32 pins across
**         various device designs.
**
**         RTOS drivers using HAL BitsIO API are simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : Bits1
**          Port                                           : PTB
**          Pins                                           : 11
**            Pin0                                         : 
**              Pin                                        : ADC0_SE6/TSI0_IN4/PTB0/IRQ_8/LLWU_P4/EXTRG_IN/SPI0_SCK
**              Pin signal                                 : 
**            Pin1                                         : 
**              Pin                                        : ADC0_SE5/TSI0_IN3/DAC0_OUT/CMP0_IN3/PTB1/IRQ_9/UART0_TX/UART0_RX
**              Pin signal                                 : 
**            Pin2                                         : 
**              Pin                                        : ADC0_SE4/TSI0_IN2/PTB2/IRQ_10/LLWU_P5/UART0_RX/UART0_TX
**              Pin signal                                 : 
**            Pin3                                         : 
**              Pin                                        : PTB3/IRQ_14/I2C0_SCL/UART0_TX
**              Pin signal                                 : 
**            Pin4                                         : 
**              Pin                                        : PTB4/IRQ_15/LLWU_P6/I2C0_SDA/UART0_RX
**              Pin signal                                 : 
**            Pin5                                         : 
**              Pin                                        : ADC0_SE1/CMP0_IN1/PTB5/IRQ_16/TPM1_CH1/NMI_b
**              Pin signal                                 : 
**            Pin6                                         : 
**              Pin                                        : PTB6/IRQ_2/LPTMR0_ALT3/TPM0_CH3/TPM_CLKIN1
**              Pin signal                                 : 
**            Pin7                                         : 
**              Pin                                        : PTB7/IRQ_3/TPM0_CH2
**              Pin signal                                 : 
**            Pin8                                         : 
**              Pin                                        : ADC0_SE11/PTB8/TPM0_CH3
**              Pin signal                                 : 
**            Pin9                                         : 
**              Pin                                        : ADC0_SE10/PTB9/TPM0_CH2
**              Pin signal                                 : 
**            Pin10                                        : 
**              Pin                                        : ADC0_SE9/TSI0_IN7/PTB10/TPM0_CH1
**              Pin signal                                 : 
**          Direction                                      : Output
**          Initialization                                 : 
**            Init. direction                              : Output
**            Init. value                                  : 00000000
**            Auto initialization                          : yes
**          Safe mode                                      : no
**     Contents    :
**         Init   - LDD_TDeviceData* Bits1_Init(LDD_TUserData *UserDataPtr);
**         GetVal - uint32_t Bits1_GetVal(LDD_TDeviceData *DeviceDataPtr);
**         PutVal - void Bits1_PutVal(LDD_TDeviceData *DeviceDataPtr, uint32_t Val);
**         GetBit - LDD_TError Bits1_GetBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit, bool...
**         PutBit - LDD_TError Bits1_PutBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit, bool Val);
**         SetBit - LDD_TError Bits1_SetBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit);
**         ClrBit - LDD_TError Bits1_ClrBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit);
**         NegBit - LDD_TError Bits1_NegBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit);
**
**     (c) 2012 by Freescale
** ###################################################################*/
/*!
** @file Bits1.h
** @version 01.00
** @date 2014-02-19, 02:32, # CodeGen: 27
** @brief
**         The HAL BitsIO component provides a low level API for unified
**         access to general purpose digital input/output 32 pins across
**         various device designs.
**
**         RTOS drivers using HAL BitsIO API are simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup Bits1_module Bits1 module documentation
**  @{
*/         

#ifndef __Bits1_H
#define __Bits1_H

/* MODULE Bits1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "IO_Map.h"
#include "GPIO_PDD.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 



/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define Bits1_PRPH_BASE_ADDRESS  0x400FF040U
  
/*! Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods. */
#define Bits1_DeviceData  ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_Bits1_ID))

/* Methods configuration constants - generated for all enabled component's methods */
#define Bits1_Init_METHOD_ENABLED      /*!< Init method of the component Bits1 is enabled (generated) */
#define Bits1_GetVal_METHOD_ENABLED    /*!< GetVal method of the component Bits1 is enabled (generated) */
#define Bits1_PutVal_METHOD_ENABLED    /*!< PutVal method of the component Bits1 is enabled (generated) */
#define Bits1_GetBit_METHOD_ENABLED    /*!< GetBit method of the component Bits1 is enabled (generated) */
#define Bits1_PutBit_METHOD_ENABLED    /*!< PutBit method of the component Bits1 is enabled (generated) */
#define Bits1_SetBit_METHOD_ENABLED    /*!< SetBit method of the component Bits1 is enabled (generated) */
#define Bits1_ClrBit_METHOD_ENABLED    /*!< ClrBit method of the component Bits1 is enabled (generated) */
#define Bits1_NegBit_METHOD_ENABLED    /*!< NegBit method of the component Bits1 is enabled (generated) */

/* Definition of implementation constants */
#define Bits1_MODULE_BASE_ADDRESS FPTB_BASE_PTR /*!< Name of macro used as the base address */
#define Bits1_PORTCONTROL_BASE_ADDRESS PORTB_BASE_PTR /*!< Name of macro used as the base address */
#define Bits1_PORT_MASK 0x07FFU        /*!< Mask of the allocated pin from the port */
#define Bits1_PORT_VALID_VALUE_MASK 0x07FF /*!< Mask of the allocated pins from the port as the first pin would be zero i.e. valid bits to be set in method PutVal */
#define Bits1_PIN_ALLOC_0_MASK 0x01    /*!< Mask of the first allocated pin from the port */
#define Bits1_PIN_ALLOC_0_INDEX 0U     /*!< The index of the first allocated pin from the port */



/*
** ===================================================================
**     Method      :  Bits1_Init (component BitsIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* Bits1_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  Bits1_GetVal (component BitsIO_LDD)
*/
/*!
**     @brief
**         Returns the value of the Input/Output component. If the
**         direction is [input] then reads the input value of the pins
**         and returns it. If the direction is [output] then returns
**         the last written value (see <Safe mode> property for
**         limitations).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Input value
*/
/* ===================================================================*/
uint32_t Bits1_GetVal(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  Bits1_PutVal (component BitsIO_LDD)
*/
/*!
**     @brief
**         Specified value is passed to the Input/Output component. If
**         the direction is [input] saves the value to a memory or a
**         register, this value will be written to the pins after
**         switching to the output mode - using [SetDir(TRUE)] (see
**         <Safe mode> property for limitations). If the direction is
**         [output] it writes the value to the pins. (Method is
**         available only if the Direction = _[output]_ or
**         _[input/output]_).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Val             - Output value
*/
/* ===================================================================*/
void Bits1_PutVal(LDD_TDeviceData *DeviceDataPtr, uint32_t Val);

/*
** ===================================================================
**     Method      :  Bits1_GetBit (component BitsIO_LDD)
*/
/*!
**     @brief
**         Returns the value of the specified bit/pin of the
**         Input/Output component. If the direction is [input] then it
**         reads the input value of the pin and returns it. If the
**         direction is [output] then it returns the last written value
**         (see <Safe mode> property for limitations).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Bit             - Bit/pin number to read
**     @param
**         BitVal          - The returned value: 
**                           <false> - logical "0" (Low level)
**                           <true> - logical "1" (High level)
**     @return
**                         - Error code, possible values:
**                           ERR_OK - OK
**                           ERR_PARAM_MASK - Invalid pin index
**                           ERR_VALUE - Invalid output parameter
*/
/* ===================================================================*/
LDD_TError Bits1_GetBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit, bool *BitVal);

/*
** ===================================================================
**     Method      :  Bits1_PutBit (component BitsIO_LDD)
*/
/*!
**     @brief
**         Specified value is passed to the specified bit/pin of the
**         Input/Output component. If the direction is [input] it saves
**         the value to a memory or register, this value will be
**         written to the pin after switching to the output mode -
**         using [SetDir(TRUE)] (see <Safe mode> property for
**         limitations). If the direction is [output] it writes the
**         value to the pin. (Method is available only if the Direction
**         = _[output]_ or _[input/output]_).
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure pointer.
**     @param
**         Bit             - Bit/pin number
**     @param
**         Val             - A new bit value. Possible values:
**                           <false> - logical "0" (Low level)
**                           <true> - logical "1" (High level)
**     @return
**                         - Error code, possible values:
**                           ERR_OK - OK
**                           ERR_PARAM_MASK - Invalid bit index
*/
/* ===================================================================*/
LDD_TError Bits1_PutBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit, bool Val);

/*
** ===================================================================
**     Method      :  Bits1_SetBit (component BitsIO_LDD)
*/
/*!
**     @brief
**         Sets (to one) the specified bit of the Input/Output
**         component. It is the same as [PutBit(Bit, TRUE)]. (Method is
**         available only if the Direction = _[output]_ or
**         _[input/output]_).
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure pointer.
**     @param
**         Bit             - Bit/pin number to set
**     @return
**                         - Error code, possible values:
**                           ERR_OK - OK
**                           ERR_PARAM_MASK - Invalid pin mask
*/
/* ===================================================================*/
LDD_TError Bits1_SetBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit);

/*
** ===================================================================
**     Method      :  Bits1_ClrBit (component BitsIO_LDD)
*/
/*!
**     @brief
**         Clears (sets to zero) the specified bit of the Input/Output
**         component. It is the same as [PutBit(Bit, FALSE)]. (Method
**         is available only if the Direction = _[output]_ or
**         _[input/output]_).
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure pointer.
**     @param
**         Bit             - Bit/pin number to clear
**     @return
**                         - Error code, possible values:
**                           ERR_OK - OK
**                           ERR_PARAM_MASK - Invalid pin mask
*/
/* ===================================================================*/
LDD_TError Bits1_ClrBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit);

/*
** ===================================================================
**     Method      :  Bits1_NegBit (component BitsIO_LDD)
*/
/*!
**     @brief
**         Negates (inverts) the specified bit of the Input/Output
**         component. It is the same as [PutBit(Bit,!GetBit(Bit))].
**         (Method is available only if the Direction = _[output]_ or
**         _[input/output]_).
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure pointer.
**     @param
**         Bit             - Bit/pin number to invert
**     @return
**                         - Error code, possible values:
**                           ERR_OK - OK
**                           ERR_PARAM_MASK - Invalid pin mask
*/
/* ===================================================================*/
LDD_TError Bits1_NegBit(LDD_TDeviceData *DeviceDataPtr, uint8_t Bit);

/* END Bits1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __Bits1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.06]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
